# Use root/example as user/password credentials
version: '3.8'


services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'concesionario-ulpgc'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'